CREATE TABLE
IF NOT EXISTS polar_prints
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    date_purchased TEXT NOT NULL,
    date_sold TEXT NOT NULL,
    purchase_price TEXT NOT NULL,
    sold_price TEXT NOT NULL
);
