CREATE TABLE
IF NOT EXISTS polar_prints
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    date_purchased TEXT NOT NUll,
    date_sold TEXT NOT NULL,
    purchase_price Text NOT NULL,
    sold_price Text NOT NULL
);
